site_name: Libro Forex

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js
  - js/math-render.js
